<header id="header">
  <div id="header-inner" class="inner wrapper">
    <h1 id="logo-wrap">
      <a href="/">
        <img src="/icon/logo.png" />
      </a>
    </h1>
    <nav id="main-nav">
      {{ header_menu('main-nav') }}
    </nav>
    <a id="mobile-nav-toggle">
      <span class="mobile-nav-toggle-bar"></span>
      <span class="mobile-nav-toggle-bar"></span>
      <span class="mobile-nav-toggle-bar"></span>
    </a>
  </div>
</header>
